version: '3.8'

services:
  app1:
    build: .
    ports:
      - "3001:3001"
    command: npm start --prefix app1
    scale: 2 # Runs 2 instances of app1

  app2:
    build: .
    ports:
      - "3002:3002"
    command: npm start --prefix app2
    scale: 1

  app3:
    build: .
    ports:
      - "3003:3003"
    command: npm start --prefix app3
    scale: 3 # Runs 3 instances of app3

  app4:
    build: .
    ports:
      - "3004:3004"
    command: npm start --prefix app4
    scale: 1

mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_DATABASE: "PrismaHospitalManagementSystem1"
    ports:
      - "3306:3306"
    networks:
      - backend
    volumes:
      - mysql_data:/var/lib/mysql
    command: >
      bash -c "
      docker-entrypoint.sh mysqld --default-authentication-plugin=mysql_native_password &
      sleep 10 &&
      mysql -uroot -proot -e 'CREATE DATABASE IF NOT EXISTS PrismaHospitalManagementSystem1;' &&
      mysql -uroot -proot -e 'CREATE DATABASE IF NOT EXISTS PrismaHospitalManagementSystem2;' &&
      mysql -uroot -proot -e 'GRANT ALL PRIVILEGES ON PrismaHospitalManagementSystem1.* TO 'root'@'%';' &&
      mysql -uroot -proot -e 'GRANT ALL PRIVILEGES ON PrismaHospitalManagementSystem2.* TO 'root'@'%';' &&
      wait
      " 
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
      interval: 10s
      retries: 5
      start_period: 30s
