version: '3.8'

services:
  user-service:
    build:
      context: ./user-service
    ports:
      - "3001:3001"
      - "50051:50051"
    depends_on:
      - redis
      - rabbitmq
    environment:
      - NODE_ENV=production
      - SERVICE_PORT=3001
      - USER_PROTO_PORT=50051
      - APPOINTMENT_PROTO_PORT=50052
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://rabbitmq
      - APPOINTMENT_DATABASE_URL=mysql://root:@192.168.179.61:3306/prismahospitalmanagementsystem1
      - USER_DATABASE_URL=mysql://root:@192.168.179.61:3306/prismahospitalmanagementsystem
      - BILLING_DATABASE_URL=mysql://root:@192.168.179.61:3306/prismahospitalmanagementsystem2
    networks:
      - backend
    command: sh -c "sleep 10 && npm run migration:user && npm run generate:user && npm start"  

  billing-service:
    build:
      context: ./billing-service
    ports:
      - "3002:3002"
    depends_on:
      - user-service
      - redis
      - rabbitmq
    environment:
      - NODE_ENV=production
      - SERVICE_PORT=3002
      - USER_PROTO_PORT=50051
      - APPOINTMENT_PROTO_PORT=50052
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://rabbitmq
      - APPOINTMENT_DATABASE_URL=mysql://root:@192.168.179.61:3306/prismahospitalmanagementsystem1
      - USER_DATABASE_URL=mysql://root:@192.168.179.61:3306/prismahospitalmanagementsystem
      - BILLING_DATABASE_URL=mysql://root:@192.168.179.61:3306/prismahospitalmanagementsystem2
    networks:
      - backend
    command: sh -c "sleep 20 && npm run migration:bill && npm run generate:bill && npm start"  

  appointment-service:
    build:
      context: ./appointment-service
    ports:
      - "3003:3003"
      - "50052:50052"
    depends_on:
      - user-service
      - redis
      - rabbitmq
    environment:
      - NODE_ENV=production
      - SERVICE_PORT=3003
      - USER_PROTO_PORT=50051
      - APPOINTMENT_PROTO_PORT=50052
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://rabbitmq
      - APPOINTMENT_DATABASE_URL=mysql://root:@192.168.179.61:3306/prismahospitalmanagementsystem1
      - USER_DATABASE_URL=mysql://root:@192.168.179.61:3306/prismahospitalmanagementsystem
      - BILLING_DATABASE_URL=mysql://root:@192.168.179.61:3306/prismahospitalmanagementsystem2
    networks:
      - backend
    command: sh -c "sleep 15 && npm run migration:appointment && npm run generate:appointment && npm start"  

  gateway:
    build:
      context: ./gateway
    ports:
      - "3000:3000"
    depends_on:
      - user-service
      - billing-service
      - appointment-service
    environment:
      - NODE_ENV=production
    networks:
      - backend

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    networks:
      - backend
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      retries: 3

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - backend
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 10s
      retries: 5

networks:
  backend:
    driver: bridge

volumes:
  mysql_data:
    driver: local
